name: Go

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - name: Set up Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: go build -v .
    - run: go get github.com/mitchellh/gox
    - run: npm ci
    - run: npx semantic-release
      env:
        GH_TOKEN: ${{secrets.GH_TOKEN}}
